# 🔬 Data exploration and preparation
In this notebook, we'll examine the dataset and create a subset of it for further analysis. The dataset was relatively clean when downloaded, though we addressed some problematic delimiter issues for you. If you're interested in tackling these issues firsthand, the original dataset is available at the [Book-Crossing Dataset](http://www2.informatik.uni-freiburg.de/~cziegler/BX/).

### 1. Loading the data
Load the three datasets and explore the data.

In [4]:
import pandas as pd

df_books_ratings = pd.read_csv('data/BX-Book-Ratings.csv', sep=';', encoding='latin-1')
df_books = pd.read_csv('data/BX-Books.csv', low_memory=False, sep=';', encoding='latin-1')
df_users = pd.read_csv('data/BX-Users.csv', low_memory=False, sep=';', encoding='latin-1')

In [6]:
# code goes here
import pandas as pd
df = pd.read_csv('./data/Books.csv', sep=';')
df

,ISBN,Title,Author,Year,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton & Company
...,...,...,...,...,...
271374,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm)
271375,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books
271376,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco
271377,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press
271378,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages

### 2. Cleaning the data
Ensure that all reviews are linked to a book. Investigate whether there are any reviews that lack a corresponding book or user. Verify the accuracy of author names and identify any anomalies, such as users who have submitted an unusually high number of reviews. Describe the process you followed to clean the data.

In [7]:
# code goes here

### 3. Subsetting the data
The publication accompanied with this dataset [Improving Recommendation Lists Through Topic Diversification](http://www2.informatik.uni-freiburg.de/~cziegler/BX/WWW-2005-Preprint.pdf) by Cai-Nicolas Ziegler, Sean M. McNee, Joseph A. Konstan, Georg Lausen; describes the process of subsetting (condensation steps) the dataset as follows (p5): 

> Hence, we discarded all books missing taxonomic descriptions, along with all ratings referring to them. Next, we also removed book titles with fewer than 20 overall mentions. Only community members with at least five ratings each were kept. 

Investigate the significance of these parameters for the dataset as a whole. Additionally, decide whether to include implicit ratings (where Book-Rating equals 0) in your final dataset. Consider the potential consequences of this choice. Would you opt to exclude them prior to assessing other parameters, or would it be more appropriate to exclude them later?

Although the publication outlines the expected dimensions of the resulting dataset, it's acceptable if your findings vary at this stage.

In [8]:
# code goes here

df = df_books_ratings

# this combination worked pretty well 
df = df[df['Book-Rating'] != 0]

x = df['ISBN'].value_counts() >= 20
idx = x[x].index
ratings = df[df['ISBN'].isin(idx)]

x = ratings['User-ID'].value_counts() >= 10
idx = x[x].index
df_book_ratings_final = ratings[ratings['User-ID'].isin(idx)]
df_book_ratings_final.shape

(41337, 3)

### 4. Extra step
Examine the `BX-Books.csv` file specifically for the book Robots and _Empire by Isaac Asimov_. Identify any issues you come across. Would you address these issues?

Given that this could pose a problem for our dataset, consider how you would resolve it. You may need to revisit step 2 if you decide to undertake this additional step.

In [9]:
# code goes here
df_books[df_books['Book-Title'] == 'Robots and Empire']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
19463,0586062009,Robots and Empire,Isaac Asimov,1986,HarperCollins,http://images.amazon.com/images/P/0586062009.0...,http://images.amazon.com/images/P/0586062009.0...,http://images.amazon.com/images/P/0586062009.0...
83090,0345328949,Robots and Empire,Isaac Asimov,1991,Del Rey Books,http://images.amazon.com/images/P/0345328949.0...,http://images.amazon.com/images/P/0345328949.0...,http://images.amazon.com/images/P/0345328949.0...
136152,0385190921,Robots and Empire,Isaac Asimov,1985,Smithmark Pub,http://images.amazon.com/images/P/0385190921.0...,http://images.amazon.com/images/P/0385190921.0...,http://images.amazon.com/images/P/0385190921.0...

### 5. Save the new dataset(s)
Save the dataset(s) in distinct named CSV-files for later usage. Move the file(s) to the data directory.

In [ ]:
# code goes here
df_books.to_csv('final_data')