# 📚 Recommendations based on average ratings
You will create your first recommendations using average ratings. This method highlights books with high reader ratings, combining popularity with quality. You'll calculate each book's average rating and choose the top-rated ones for your recommendations.

### 1. Calculate the average ratings
Calculate the average ratings and the number of reviews (count) for the books in your new dataset(s).

In [6]:
# code goes here
import pandas as pd
df1 = pd.read_csv('data/BX-Book-Ratings.csv', sep=';', encoding='latin-1')
df = df1.groupby(['ISBN'])['Book-Rating'].agg(['mean']).reset_index()
df = df.sort_values(by="mean", ascending=False)

In [7]:
df1

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149774   276704   1563526298            9
1149775   276706   0679447156            0
1149776   276709   0515107662           10
1149777   276721   0590442449           10
1149778   276723  05162443314            8

[1149779 rows x 3 columns]

In [8]:
df

                 ISBN  mean
102530     0440445426  10.0
102548     044045459X  10.0
340496   PS35730526B6  10.0
340506   SBN67001026X  10.0
102621     044047731X  10.0
...               ...   ...
340512  TBR0345359321   0.0
340511  T110105705048   0.0
340510  T110105305048   0.0
340508  SELFPUBLISHED   0.0
17         )440206529   0.0

[340555 rows x 2 columns]

### 2. Save the recommendations
Choose the top 10 based on ratings and save them as `recommendations-ratings-avg.csv`, replacing the existing file in the app directory. Ensure the file includes the columns: `ISBN;mean`. After you have saved it you can refresh Streamlit to see the results

In [10]:
# code goes here
df.to_csv('recomendations_ratings_avg.csv')

### 3. Reflect on the recommendations
Examine the average rating and number of reviews for the top 10 books. Reflect on why solely using average ratings isn't the best method for recommendations.